--------------------------------------------------------
--  Arquivo criado - terça-feira-dezembro-02-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "CF_USER"."CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0), 
	"NOME" VARCHAR2(100 BYTE), 
	"TIPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CF_USER"."PK_CATEGORIA" ON "CF_USER"."CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_CATEGORIA_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CF_USER"."TRG_CATEGORIA_BI" 
BEFORE INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
    IF :NEW.id_categoria IS NULL THEN
        SELECT seq_categoria.NEXTVAL INTO :NEW.id_categoria FROM dual;
    END IF;
END;

/
ALTER TRIGGER "CF_USER"."TRG_CATEGORIA_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "CF_USER"."CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."CATEGORIA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."CATEGORIA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."CATEGORIA" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."CATEGORIA" ADD CONSTRAINT "CK_CATEGORIA_TIPO" CHECK (TIPO IN ('GASTO', 'RECEBIMENTO')) ENABLE;
  ALTER TABLE "CF_USER"."CATEGORIA" ADD CONSTRAINT "PK_CATEGORIA" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "CF_USER"."CATEGORIA" ADD CONSTRAINT "FK_CATEGORIA_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "CF_USER"."USUARIO" ("ID_USUARIO") ENABLE;
