--------------------------------------------------------
--  Arquivo criado - terça-feira-dezembro-02-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GASTO
--------------------------------------------------------

  CREATE TABLE "CF_USER"."GASTO" 
   (	"ID_GASTO" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0), 
	"ID_CATEGORIA" NUMBER(10,0), 
	"DESCRICAO" VARCHAR2(300 BYTE), 
	"VALOR" NUMBER(10,2), 
	"DATA_GASTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GASTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CF_USER"."PK_GASTO" ON "CF_USER"."GASTO" ("ID_GASTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_GASTO_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CF_USER"."TRG_GASTO_BI" 
BEFORE INSERT ON GASTO
FOR EACH ROW
BEGIN
    IF :NEW.id_gasto IS NULL THEN
        SELECT seq_gasto.NEXTVAL INTO :NEW.id_gasto FROM dual;
    END IF;
END;

/
ALTER TRIGGER "CF_USER"."TRG_GASTO_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table GASTO
--------------------------------------------------------

  ALTER TABLE "CF_USER"."GASTO" MODIFY ("ID_GASTO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."GASTO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."GASTO" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."GASTO" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."GASTO" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."GASTO" MODIFY ("DATA_GASTO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."GASTO" ADD CONSTRAINT "CK_GASTO_VALOR" CHECK (valor >= 0) ENABLE;
  ALTER TABLE "CF_USER"."GASTO" ADD CONSTRAINT "PK_GASTO" PRIMARY KEY ("ID_GASTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GASTO
--------------------------------------------------------

  ALTER TABLE "CF_USER"."GASTO" ADD CONSTRAINT "FK_GASTO_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "CF_USER"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "CF_USER"."GASTO" ADD CONSTRAINT "FK_GASTO_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "CF_USER"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
