--------------------------------------------------------
--  Arquivo criado - terça-feira-dezembro-02-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECEBIMENTO
--------------------------------------------------------

  CREATE TABLE "CF_USER"."RECEBIMENTO" 
   (	"ID_RECEBIMENTO" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0), 
	"ID_CATEGORIA" NUMBER(10,0), 
	"DESCRICAO" VARCHAR2(300 BYTE), 
	"VALOR" NUMBER(10,2), 
	"DATA_RECEB" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RECEBIMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CF_USER"."PK_RECEBIMENTO" ON "CF_USER"."RECEBIMENTO" ("ID_RECEBIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEBIMENTO_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CF_USER"."TRG_RECEBIMENTO_BI" 
BEFORE INSERT ON recebimento
FOR EACH ROW
BEGIN
    IF :NEW.id_recebimento IS NULL THEN
        SELECT seq_recebimento.NEXTVAL INTO :NEW.id_recebimento FROM dual;
    END IF;
END;

/
ALTER TRIGGER "CF_USER"."TRG_RECEBIMENTO_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table RECEBIMENTO
--------------------------------------------------------

  ALTER TABLE "CF_USER"."RECEBIMENTO" MODIFY ("ID_RECEBIMENTO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."RECEBIMENTO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."RECEBIMENTO" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."RECEBIMENTO" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."RECEBIMENTO" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."RECEBIMENTO" MODIFY ("DATA_RECEB" NOT NULL ENABLE);
  ALTER TABLE "CF_USER"."RECEBIMENTO" ADD CONSTRAINT "CK_RECEB_VALOR" CHECK (valor >= 0) ENABLE;
  ALTER TABLE "CF_USER"."RECEBIMENTO" ADD CONSTRAINT "PK_RECEBIMENTO" PRIMARY KEY ("ID_RECEBIMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEBIMENTO
--------------------------------------------------------

  ALTER TABLE "CF_USER"."RECEBIMENTO" ADD CONSTRAINT "FK_RECEB_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "CF_USER"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "CF_USER"."RECEBIMENTO" ADD CONSTRAINT "FK_RECEB_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "CF_USER"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
