PROMPT === 1) TABELAS ===
@TABELAS/T_USUARIO.sql
@TABELAS/T_CATEGORIA.sql
@TABELAS/T_GASTO.sql
@TABELAS/T_RECEBIMENTO.sql

PROMPT === 2) SEQUENCES ===
@SEQUENCES/SEQ_USUARIO.sql
@SEQUENCES/SEQ_CATEGORIA.sql
@SEQUENCES/SEQ_GASTO.sql
@SEQUENCES/SEQ_RECEBIMENTO.sql

PROMPT === 3) TRIGGERS ===
@TRIGGERS/TRG_USUARIO_BI.sql
@TRIGGERS/TRG_CATEGORIA_BI.sql
@TRIGGERS/TRG_GASTO_BI.sql
@TRIGGERS/TRG_RECEBIMENTO_BI.sql

PROMPT === PRONTO: estrutura criada com sucesso! ===